import type { Player, PlayerRoleCode } from "@/types";

const ROLE_BY_PLAYER_ID: Record<string, PlayerRoleCode> = {
  "alvaro-fernandez": "POR",
  guzman: "LD",
  victor: "LI",
  babin: "DFC",
  "edu-cortina": "MCD",
  "luis-alcalde": "MC",
  "kevin-bautista": "MCO",
  "jose-santamaria": "DC",
  "javi-cueto": "MP",
  "raul-rubio": "ED",
  grigore: "DFC",
  nando: "POR",
  cayarga: "LI",
  "chukwuma-eze": "DC",
  "adri-gomez": "EI",
  quicala: "MCO",
  gete: "DFC",
  natalio: "SD",
  campadal: "MC",
  uzkudun: "DFC",
  "isi-ros": "EI",
  rivera: "MC",
  carmona: "DFC",
  osky: "ED",
  "fem-paula-madrazo": "POR",
  "fem-elena-casao": "POR",
  "fem-andrea-fernandez": "DFC",
  "fem-goretti-neira": "DFC",
  "fem-elizabet-rodriguez": "DFC",
  "fem-lucia-ayuso": "LD",
  "fem-mirdja-rodriguez": "LI",
  "fem-tayre-fernandez": "DFC",
  "fem-maria-iglesias": "DFC",
  "fem-laura-lobo": "MC",
  "fem-carmen-penalver": "MC",
  "fem-paula-martinez": "MC",
  "fem-laura-tomas": "MC",
  "fem-sara-randez": "MCO",
  "fem-nuria-torres": "MC",
  "fem-tatiana-rodriguez": "MCO",
  "fem-elena-pradilla": "MCD",
  "fem-cristina-menendez": "DC",
  "fem-noa-diaz": "EI",
  "fem-marina-monteserin": "DC",
  "fem-amaya-coleman": "SD",
  "fem-daniela-gonzalez": "ED",
  "fem-paula-carballo": "DC",
  "fem-sarina-heeb": "SD",
};

export function getPlayerRole(player: Pick<Player, "id" | "position" | "bio">): PlayerRoleCode {
  return ROLE_BY_PLAYER_ID[player.id] ?? "MC";
}
