/**
 * Generates data/resultados-2526-grupo2.json from the official 25/26 double round-robin
 * and Wikipedia's published results matrix (updated 23 May 2026).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const TEAMS = [
  { id: "alcorcon", name: "AD Alcorcón", abbr: "ALC" },
  { id: "algeciras", name: "Algeciras CF", abbr: "ALG" },
  { id: "antequera", name: "Antequera CF", abbr: "ANT" },
  { id: "atletico-madrileno", name: "Atlético Madrileño", abbr: "ATM" },
  { id: "atletico-sanluqueno", name: "Atlético Sanluqueño", abbr: "ATS" },
  { id: "betis-deportivo", name: "Betis Deportivo", abbr: "BET" },
  { id: "cartagena", name: "FC Cartagena", abbr: "CAR" },
  { id: "eldense", name: "CD Eldense", abbr: "ELD" },
  { id: "europa", name: "CE Europa", abbr: "EUR" },
  { id: "gimnastic", name: "Gimnàstic de Tarragona", abbr: "GIM" },
  { id: "hercules", name: "Hércules CF", abbr: "HER" },
  { id: "ibiza", name: "UD Ibiza", abbr: "IBI" },
  { id: "torremolinos", name: "Juventud Torremolinos CF", abbr: "JUV" },
  { id: "marbella", name: "Marbella FC", abbr: "MAR" },
  { id: "real-murcia", name: "Real Murcia CF", abbr: "RMU" },
  { id: "sabadell", name: "CE Sabadell FC", abbr: "SAB" },
  { id: "sevilla-atletico", name: "Sevilla Atlético", abbr: "SVA" },
  { id: "tarazona", name: "SD Tarazona", abbr: "TAR" },
  { id: "teruel", name: "CD Teruel", abbr: "TER" },
  { id: "villarreal-b", name: "Villarreal CF B", abbr: "VIB" },
] as const;

/** Local row → visitante column. Source: Wikipedia Primera Federación 2025-26 Grupo II. */
const MATRIX: Record<string, Record<string, string>> = {
  ALC: {
    ALG: "0-0",
    ANT: "2-1",
    ATM: "0-1",
    ATS: "0-0",
    BET: "3-0",
    CAR: "1-1",
    ELD: "1-1",
    EUR: "0-1",
    GIM: "1-1",
    HER: "4-0",
    IBI: "2-2",
    JUV: "1-1",
    MAR: "6-2",
    RMU: "1-0",
    SAB: "0-3",
    SVA: "0-0",
    TAR: "1-0",
    TER: "2-1",
    VIB: "2-3",
  },
  ALG: {
    ALC: "1-0",
    ANT: "1-0",
    ATM: "1-0",
    ATS: "3-0",
    BET: "2-0",
    CAR: "2-2",
    ELD: "1-1",
    EUR: "2-3",
    GIM: "1-0",
    HER: "0-2",
    IBI: "0-0",
    JUV: "1-0",
    MAR: "0-0",
    RMU: "1-0",
    SAB: "1-2",
    SVA: "3-0",
    TAR: "1-0",
    TER: "0-0",
    VIB: "0-0",
  },
  ANT: {
    ALC: "1-2",
    ALG: "2-0",
    ATM: "2-4",
    ATS: "2-0",
    BET: "2-1",
    CAR: "0-0",
    ELD: "2-1",
    EUR: "0-2",
    GIM: "4-2",
    HER: "1-1",
    IBI: "0-3",
    JUV: "3-1",
    MAR: "3-1",
    RMU: "0-2",
    SAB: "0-0",
    SVA: "1-1",
    TAR: "2-3",
    TER: "1-0",
    VIB: "0-1",
  },
  ATM: {
    ALC: "0-0",
    ALG: "3-1",
    ANT: "3-2",
    ATS: "0-0",
    BET: "3-1",
    CAR: "2-0",
    ELD: "1-1",
    EUR: "2-0",
    GIM: "1-2",
    HER: "0-0",
    IBI: "2-0",
    JUV: "3-1",
    MAR: "5-4",
    RMU: "1-1",
    SAB: "4-3",
    SVA: "1-0",
    TAR: "1-1",
    TER: "3-0",
    VIB: "1-1",
  },
  ATS: {
    ALC: "0-1",
    ALG: "0-1",
    ANT: "1-3",
    ATM: "1-2",
    BET: "1-4",
    CAR: "3-0",
    ELD: "1-4",
    EUR: "1-3",
    GIM: "1-0",
    HER: "1-1",
    IBI: "0-0",
    JUV: "0-2",
    MAR: "3-2",
    RMU: "0-2",
    SAB: "2-2",
    SVA: "0-0",
    TAR: "2-1",
    TER: "1-1",
    VIB: "1-4",
  },
  BET: {
    ALC: "2-1",
    ALG: "1-1",
    ANT: "1-0",
    ATM: "0-2",
    ATS: "1-0",
    CAR: "0-1",
    ELD: "0-1",
    EUR: "2-2",
    GIM: "2-2",
    HER: "2-1",
    IBI: "3-2",
    JUV: "2-0",
    MAR: "0-1",
    RMU: "1-2",
    SAB: "1-2",
    SVA: "3-1",
    TAR: "3-0",
    TER: "2-2",
    VIB: "1-4",
  },
  CAR: {
    ALC: "2-1",
    ALG: "2-0",
    ANT: "1-0",
    ATM: "3-2",
    ATS: "1-0",
    BET: "2-2",
    ELD: "0-0",
    EUR: "2-2",
    GIM: "1-0",
    HER: "2-1",
    IBI: "1-4",
    JUV: "3-0",
    MAR: "2-1",
    RMU: "0-1",
    SAB: "0-0",
    SVA: "1-0",
    TAR: "3-0",
    TER: "0-0",
    VIB: "0-2",
  },
  ELD: {
    ALC: "2-2",
    ALG: "3-2",
    ANT: "1-3",
    ATM: "2-1",
    ATS: "1-0",
    BET: "2-0",
    CAR: "2-1",
    EUR: "3-0",
    GIM: "4-1",
    HER: "2-0",
    IBI: "3-0",
    JUV: "3-3",
    MAR: "3-1",
    RMU: "1-1",
    SAB: "2-1",
    SVA: "1-0",
    TAR: "1-0",
    TER: "2-0",
    VIB: "1-0",
  },
  EUR: {
    ALC: "0-0",
    ALG: "0-3",
    ANT: "2-0",
    ATM: "2-2",
    ATS: "2-1",
    BET: "5-2",
    CAR: "2-0",
    ELD: "1-1",
    GIM: "2-0",
    HER: "1-1",
    IBI: "3-2",
    JUV: "2-3",
    MAR: "2-1",
    RMU: "0-2",
    SAB: "2-0",
    SVA: "1-1",
    TAR: "1-1",
    TER: "1-0",
    VIB: "3-3",
  },
  GIM: {
    ALC: "1-2",
    ALG: "2-1",
    ANT: "0-1",
    ATM: "0-3",
    ATS: "1-3",
    BET: "2-2",
    CAR: "2-0",
    ELD: "3-0",
    EUR: "2-1",
    HER: "2-2",
    IBI: "1-0",
    JUV: "2-0",
    MAR: "1-0",
    RMU: "2-1",
    SAB: "0-0",
    SVA: "2-1",
    TAR: "2-1",
    TER: "0-1",
    VIB: "0-1",
  },
  HER: {
    ALC: "0-0",
    ALG: "0-1",
    ANT: "0-1",
    ATM: "3-0",
    ATS: "0-0",
    BET: "2-0",
    CAR: "2-0",
    ELD: "2-1",
    EUR: "1-0",
    GIM: "1-1",
    IBI: "2-1",
    JUV: "2-1",
    MAR: "2-0",
    RMU: "2-0",
    SAB: "1-5",
    SVA: "0-0",
    TAR: "1-0",
    TER: "3-1",
    VIB: "2-1",
  },
  IBI: {
    ALC: "2-2",
    ALG: "3-0",
    ANT: "1-1",
    ATM: "2-0",
    ATS: "4-0",
    BET: "0-0",
    CAR: "3-1",
    ELD: "0-1",
    EUR: "1-1",
    GIM: "0-2",
    HER: "2-1",
    JUV: "2-1",
    MAR: "0-1",
    RMU: "2-0",
    SAB: "2-0",
    SVA: "0-1",
    TAR: "1-0",
    TER: "0-1",
    VIB: "0-0",
  },
  JUV: {
    ALC: "1-0",
    ALG: "1-1",
    ANT: "1-1",
    ATM: "3-1",
    ATS: "1-0",
    BET: "1-2",
    CAR: "0-1",
    ELD: "1-1",
    EUR: "0-1",
    GIM: "2-0",
    HER: "2-2",
    IBI: "3-0",
    MAR: "1-1",
    RMU: "1-3",
    SAB: "1-1",
    SVA: "2-0",
    TAR: "2-1",
    TER: "2-2",
    VIB: "0-3",
  },
  MAR: {
    ALC: "1-2",
    ALG: "4-1",
    ANT: "0-1",
    ATM: "0-1",
    ATS: "1-0",
    BET: "1-1",
    CAR: "0-0",
    ELD: "1-0",
    EUR: "0-2",
    GIM: "2-0",
    HER: "0-1",
    IBI: "1-1",
    JUV: "0-1",
    RMU: "2-1",
    SAB: "0-1",
    SVA: "3-0",
    TAR: "0-1",
    TER: "3-1",
    VIB: "0-1",
  },
  RMU: {
    ALC: "2-1",
    ALG: "0-2",
    ANT: "2-3",
    ATM: "2-1",
    ATS: "0-1",
    BET: "1-2",
    CAR: "1-2",
    ELD: "3-1",
    EUR: "3-2",
    GIM: "1-1",
    HER: "0-2",
    IBI: "2-1",
    JUV: "1-1",
    MAR: "0-0",
    SAB: "1-1",
    SVA: "1-0",
    TAR: "0-0",
    TER: "1-1",
    VIB: "1-1",
  },
  SAB: {
    ALC: "0-0",
    ALG: "3-1",
    ANT: "0-1",
    ATM: "2-0",
    ATS: "2-0",
    BET: "1-3",
    CAR: "0-0",
    ELD: "0-0",
    EUR: "4-0",
    GIM: "0-0",
    HER: "1-0",
    IBI: "2-0",
    JUV: "2-2",
    MAR: "5-0",
    RMU: "2-2",
    SVA: "1-0",
    TAR: "0-0",
    TER: "0-0",
    VIB: "1-0",
  },
  SVA: {
    ALC: "1-1",
    ALG: "0-2",
    ANT: "1-1",
    ATM: "1-1",
    ATS: "2-1",
    BET: "1-0",
    CAR: "0-0",
    ELD: "2-2",
    EUR: "0-1",
    GIM: "1-2",
    HER: "2-0",
    IBI: "1-2",
    JUV: "1-1",
    MAR: "1-0",
    RMU: "0-1",
    SAB: "1-2",
    TAR: "0-1",
    TER: "0-1",
    VIB: "0-0",
  },
  TAR: {
    ALC: "2-0",
    ALG: "2-2",
    ANT: "1-0",
    ATM: "1-4",
    ATS: "0-2",
    BET: "1-0",
    CAR: "0-0",
    ELD: "1-2",
    EUR: "0-0",
    GIM: "2-0",
    HER: "2-2",
    IBI: "0-0",
    JUV: "0-0",
    MAR: "0-0",
    RMU: "1-0",
    SAB: "0-2",
    SVA: "2-0",
    TER: "3-2",
    VIB: "2-1",
  },
  TER: {
    ALC: "1-2",
    ALG: "1-0",
    ANT: "0-1",
    ATM: "0-0",
    ATS: "0-0",
    BET: "0-0",
    CAR: "1-2",
    ELD: "1-1",
    EUR: "1-0",
    GIM: "1-0",
    HER: "2-1",
    IBI: "1-0",
    JUV: "0-1",
    MAR: "1-0",
    RMU: "0-0",
    SAB: "0-1",
    SVA: "1-0",
    TAR: "0-0",
    VIB: "1-0",
  },
  VIB: {
    ALC: "1-0",
    ALG: "4-0",
    ANT: "1-1",
    ATM: "1-3",
    ATS: "2-0",
    BET: "4-1",
    CAR: "1-0",
    ELD: "2-0",
    EUR: "3-3",
    GIM: "0-0",
    HER: "1-0",
    IBI: "0-0",
    JUV: "2-2",
    MAR: "3-1",
    RMU: "1-1",
    SAB: "1-1",
    SVA: "2-0",
    TAR: "1-1",
    TER: "1-2",
  },
};

function parseScore(score: string): [number, number] {
  const [home, away] = score.split("-").map(Number);
  return [home, away];
}

function generateRoundRobinPairs(teamIds: readonly string[]): Array<Array<[string, string]>> {
  const list = [...teamIds];
  if (list.length % 2 !== 0) list.push("__bye__");
  const n = list.length;
  const rounds: Array<Array<[string, string]>> = [];

  for (let round = 0; round < n - 1; round++) {
    const pairs: Array<[string, string]> = [];
    for (let i = 0; i < n / 2; i++) {
      const a = list[i];
      const b = list[n - 1 - i];
      if (a !== "__bye__" && b !== "__bye__") pairs.push([a, b]);
    }
    rounds.push(pairs);
    const fixed = list[0];
    const rotated = [fixed, list[n - 1], ...list.slice(1, n - 1)];
    list.splice(0, list.length, ...rotated);
  }

  return rounds;
}

function kickoffForRound(round: number): { fecha: string; hora: string } {
  const start = new Date(Date.UTC(2025, 7, 31, 18, 30));
  const date = new Date(start);
  date.setUTCDate(start.getUTCDate() + (round - 1) * 7);
  const fecha = date.toISOString().slice(0, 10);
  return { fecha, hora: "18:30" };
}

const teamIds = TEAMS.map((team) => team.id);
const firstLeg = generateRoundRobinPairs(teamIds);
const secondLeg = firstLeg.map((round) => round.map(([home, away]) => [away, home] as [string, string]));
const allRounds = [...firstLeg, ...secondLeg];

const jornadas = allRounds.map((pairs, index) => {
  const round = index + 1;
  const { fecha, hora } = kickoffForRound(round);

  const partidos = pairs.map(([homeId, awayId]) => {
    const home = TEAMS.find((team) => team.id === homeId)!;
    const away = TEAMS.find((team) => team.id === awayId)!;
    const score = MATRIX[home.abbr][away.abbr];
    const [goles_local, goles_visitante] = parseScore(score);
    return {
      fecha,
      hora,
      local: home.name,
      visitante: away.name,
      goles_local,
      goles_visitante,
      resultado: score,
    };
  });

  return { jornada: round, partidos };
});

const output = {
  competicion: "Primera Federación Grupo 2 2025-2026",
  jornadas: [...jornadas].reverse(),
};

const target = join(process.cwd(), "data/resultados-2526-grupo2.json");
writeFileSync(target, `${JSON.stringify(output, null, 2)}\n`, "utf8");
console.log(`Wrote ${target} (${jornadas.length} jornadas)`);
