import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const RAI_TEAM_ID = "real-aviles-industrial";
const RAI_FEM_TEAM_ID = "real-aviles-industrial-femenino";

const GRUPO1_TEAM_IDS = [
  RAI_TEAM_ID,
  "ferrol",
  "lugo",
  "pontevedra",
  "zamora",
  "arenteiro",
  "unionistas",
  "ponferradina",
  "castilla",
  "tenerife",
  "talavera",
  "merida",
  "celta-fortuna",
  "cacereno",
  "guadalajara",
  "ourense",
  "arenas",
  "barakaldo",
  "athletic-bilbao-b",
  "osasuna-promesas",
] as const;

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const estadioDir = join(root, "public/estadio");
const manifestPath = join(root, "lib/stadium-manifest.ts");

const IMAGE_EXT = /\.(jpe?g|png|webp)$/i;

const files = readdirSync(estadioDir)
  .filter((name) => IMAGE_EXT.test(name))
  .sort((a, b) => a.localeCompare(b, "es"));

const bySlug = new Map<string, string>();
for (const file of files) {
  const slug = file.replace(IMAGE_EXT, "");
  bySlug.set(slug, `/estadio/${file}`);
}

const entries: [string, string][] = [...bySlug.entries()];

if (bySlug.has(RAI_TEAM_ID) && !bySlug.has(RAI_FEM_TEAM_ID)) {
  entries.push([RAI_FEM_TEAM_ID, bySlug.get(RAI_TEAM_ID)!]);
}

const body = entries.map(([slug, path]) => `  "${slug}": "${path}",`).join("\n");

const source = `/** Generated by \`npm run sync:estadios\` from /public/estadio. Do not edit by hand. */
export const STADIUM_PATHS: Record<string, string> = {
${body}
};
`;

writeFileSync(manifestPath, source);

console.log(`Estadios sincronizados: ${bySlug.size} archivos → lib/stadium-manifest.ts`);

const missing = GRUPO1_TEAM_IDS.filter((id) => !bySlug.has(id));
const orphans = [...bySlug.keys()].filter(
  (slug) => !GRUPO1_TEAM_IDS.includes(slug as (typeof GRUPO1_TEAM_IDS)[number]),
);

if (missing.length > 0) {
  console.warn(`Faltan fotos de estadio para: ${missing.join(", ")}`);
}

if (orphans.length > 0) {
  console.warn(`Estadios sin equipo en Grupo I: ${orphans.join(", ")}`);
}
