import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const RAI_TEAM_ID = "real-aviles-industrial";
const RAI_FEM_TEAM_ID = "real-aviles-industrial-femenino";

const GRUPO1_TEAM_IDS = [
  RAI_TEAM_ID,
  "ferrol",
  "lugo",
  "pontevedra",
  "zamora",
  "arenteiro",
  "unionistas",
  "ponferradina",
  "castilla",
  "tenerife",
  "talavera",
  "merida",
  "celta-fortuna",
  "cacereno",
  "guadalajara",
  "ourense",
  "arenas",
  "barakaldo",
  "athletic-bilbao-b",
  "osasuna-promesas",
] as const;

const GRUPO2_TEAM_IDS = [
  "eldense",
  "sabadell",
  "atletico-madrileno",
  "villarreal-b",
  "europa",
  "cartagena",
  "antequera",
  "algeciras",
  "hercules",
  "real-murcia",
  "alcorcon",
  "ibiza",
  "teruel",
  "gimnastic",
  "torremolinos",
  "betis-deportivo",
  "tarazona",
  "marbella",
  "atletico-sanluqueno",
  "sevilla-atletico",
] as const;

const REQUIRED_TEAM_IDS = [...GRUPO1_TEAM_IDS, ...GRUPO2_TEAM_IDS] as const;

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const escudosDir = join(root, "public/escudos");
const manifestPath = join(root, "lib/escudo-manifest.ts");

const IMAGE_EXT = /\.(jpe?g|png|webp)$/i;

const files = readdirSync(escudosDir)
  .filter((name) => IMAGE_EXT.test(name))
  .sort((a, b) => a.localeCompare(b, "es"));

const bySlug = new Map<string, string>();
for (const file of files) {
  const slug = file.replace(IMAGE_EXT, "");
  bySlug.set(slug, `/escudos/${file}`);
}

const entries: [string, string][] = [...bySlug.entries()];

if (bySlug.has(RAI_TEAM_ID) && !bySlug.has(RAI_FEM_TEAM_ID)) {
  entries.push([RAI_FEM_TEAM_ID, bySlug.get(RAI_TEAM_ID)!]);
}

const body = entries.map(([slug, path]) => `  "${slug}": "${path}",`).join("\n");

const source = `/** Generated by \`npm run sync:escudos\` from /public/escudos. Do not edit by hand. */
export const ESCUDO_PATHS: Record<string, string> = {
${body}
};
`;

writeFileSync(manifestPath, source);

console.log(`Escudos sincronizados: ${bySlug.size} archivos → lib/escudo-manifest.ts`);

const missing = REQUIRED_TEAM_IDS.filter((id) => !bySlug.has(id));
const orphans = [...bySlug.keys()].filter(
  (slug) => !REQUIRED_TEAM_IDS.includes(slug as (typeof REQUIRED_TEAM_IDS)[number]),
);

if (missing.length > 0) {
  console.error(`Faltan escudos para: ${missing.join(", ")}`);
  process.exit(1);
}

if (orphans.length > 0) {
  console.warn(`Escudos sin equipo en mock: ${orphans.join(", ")}`);
}
